micronaut:
  application:
    name: quotesChallenge
    http:
      services:
        quotes-garden:
          url: https://quote-garden.onrender.com/
db:
  name: quotes
  collection: quotes
quote-garden:
  path: api/v3/quotes
mongodb:
  uri: mongodb://localhost:27017/quotes
  packages:
    - com.andrecastrosousa
